version: '3'
services:
    internal:
        build: ai
        volumes:
            - ./ai:/app
            - ./secret.yaml:/etc/secrets/gcloud/secret.yaml
        ports:
            - '6969:8080'
        command: "tail -f /dev/null"
        # command: "sh run.sh"
        environment:
            PORT: '8080'

    database:
        image: 'ankane/pgvector'
        volumes:
            - ./db-data:/var/lib/postgresql/data/
        # Only expose ports for debug
        # ports:
        #     - 5432:5432
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: password
            POSTGRES_DB: video_script_research

    # Not yet require this service in this application
    # unstructured:
    #     image: quay.io/unstructured-io/unstructured-api:0.0.30
    #     ports:
    #         - '8000:8000'

