version: '3'
services:
    ai:
        build: ai
        volumes:
            - ./ai:/app
            - ./ai/service-account.json:/etc/secrets/gcloud/service-account.json
            - ./static:/static
        ports:
            - '6969:8080'
        command: "tail -f /dev/null"
        environment:
            - PORT=8080
            - GOOGLE_APPLICATION_CREDENTIALS=/etc/secrets/gcloud/service-account.json

    database:
        image: 'ankane/pgvector'
        volumes:
            - ./db-data:/var/lib/postgresql/data/
        # ports:
        #     - 5432:5432
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: password
            POSTGRES_DB: video_script_research

    # Not yet require this service in this application
    # unstructured:
    #     image: quay.io/unstructured-io/unstructured-api:0.0.30
    #     ports:
    #         - '8000:8000'

